export enum PATHS {
  ACHIEVEMENTS = 'achievements',
  MINIONS = 'minions',
  TITLES = 'titles',
  MOUNTS = 'mounts',
  ORCHESTRIONS = 'orchestrions',
  FRAMES = 'frames',
  SPELLS = 'spells',
  EMOTES = 'emotes',
  BARDINGS = 'bardings',
  HAIRSTYLES = 'hairstyles',
  ARMOIRES = 'armoires',
  FASHIONS = 'fashions',
  RECORDS = 'records',
  SURVEY_RECORDS = 'survey_records',
  RELICS = 'relics',
}
